### ISSUE TITLE
Lazy load got stuck if during page load open a new tab 

### ISSUE THREAD

**Issue by amanpreet-cipl** [dkern/jquery.lazy#172]
Hello,
We used lazyload library for website in magento 2. 
Lazy load is working fine on all browsers but we rectify one case on which it stucks:
**Case** - Lazy load is not working if page not fully loaded but suddenly we navigate to next tab on same browser then return to page, images got stuck and lazy load not working but if reload the page then it starts working.
Can anyone help me on this?

**Comment by eisbehr-** [comment]
Hello!

Do you have this issue in a specific browser? Are there any errors in console?
This could be a problem of a second script/library or wrong loading on going back. If you are going to next page, the loading of the current page is stopped. If you are going back, the browser might not start loading again. So you have a half-loaded page and all not currently loaded scripts didn't work. This is not an issue of Lazy, this would be normal behavior.

**Comment by amanpreet-cipl** [comment]
Hello,
As I review this is not normal behavior. We're getting issue on all browsers.
You can check in site - http://staging.internationalenviroguard.com/
