### ISSUE TITLE
Images not loading on mobile & small problem on desktop also

### ISSUE THREAD

**Issue by MrMakaveli** [dkern/jquery.lazy#219]
Hello,
I am working on a site that uses your plugin and it seems it has some problems... so far I can't figure out if they've implemented the code wrong or if there's another issue/conflict or something.
The site is: https://www.worldofglasspipes.com/
And the problems are as follow:
1. If you scroll to "Latest products" (main page) you'll see your plugin used on a carousel (horizontal). If you click the arrow to scroll, loader image remains stuck until you do a small scroll up/down and only then they load.
2. The biggest issue is on mobile - if you switch to mobile view and do the same thing, images won't load at all, even if you scroll up or down.
Would it be too much of a bother for you to have a quick look and see if it's a problem from the plugin or the code?
Plugin seems to be loaded like this:

```
(function($) {
    "use strict";

    // lazy load images
    if($('body').hasClass('lazy-images')){
        $('img[data-src]').lazy({
            effect: "fadeIn",
            effectTime: 300,
            threshold: 0,
        });
...
```

Thanks!

**Comment by dkern** [comment]
Old issue but short answer: Lazy only listens to `scroll` by default. A slide don't use `scroll` event, nor does mobile devices.
